name: news_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.0.6+18

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  cupertino_icons: ^1.0.4
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  firebase_storage: ^10.2.5
  flutter_web_browser: ^0.16.0
  flutter_html: ^2.1.2
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  html: ^0.15.0
  flutter_svg: ^0.23.0
  html_unescape: ^2.0.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  launch_review: ^3.0.1
  line_icons: ^2.0.1
  lottie: ^1.2.1
  package_info: ^2.0.2
  path_provider: ^2.0.8
  provider: ^6.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.11
  skeleton_text: ^3.0.0
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.17
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  rounded_loading_button: ^2.0.9
  firebase_analytics: ^9.0.5
  flutter_facebook_auth: ^4.0.1
  the_apple_sign_in: ^1.1.1
  better_player: ^0.0.81
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
      
  google_mobile_ads: ^1.0.1
  facebook_audience_network: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation_files/
    - assets/translations/
    - assets/items.json
    - assets/pokemons.json
    - assets/images/
  fonts:

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900

    - family: Circular
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Circular.otf
          weight: 400
